<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <Description>Unit tests for the PhiliaContacts application.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../../tests/fixtures/legacy/**/*.json" Link="fixtures/legacy/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhiliaContacts.Business\PhiliaContacts.Business.csproj" />
    <ProjectReference Include="..\PhiliaContacts.Data\PhiliaContacts.Data.csproj" />
    <ProjectReference Include="..\PhiliaContacts.Integrations\PhiliaContacts.Integrations.csproj" />
    <ProjectReference Include="..\PhiliaContacts.Presentation.Desktop\PhiliaContacts.Presentation.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.4.1" />
  </ItemGroup>

</Project>
