//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhiliaContacts.Presentation.Desktop.Base
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen

    using System;
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppInfo
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppInfo()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhiliaContacts.Presentation.Desktop.Base.AppInfo", typeof(AppInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage all your contacts centrally and cleanly. Import from, or export to, your Android or Apple contacts using the universal vCard (Virtual Contact File) format..
        /// </summary>
        internal static string AppDescription
        {
            get
            {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Philia Contacts.
        /// </summary>
        internal static string AppDisplayName
        {
            get
            {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aaron Salisbury.
        /// </summary>
        internal static string CopyHolder
        {
            get
            {
                return ResourceManager.GetString("CopyHolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://github.com/aaron-salisbury/PhiliaContacts/issues.
        /// </summary>
        internal static string IssuesURL
        {
            get
            {
                return ResourceManager.GetString("IssuesURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://github.com/aaron-salisbury/PhiliaContacts/blob/master/license.
        /// </summary>
        internal static string LicenseURL
        {
            get
            {
                return ResourceManager.GetString("LicenseURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://github.com/aaron-salisbury/PhiliaContacts/blob/master/PrivacyPolicy.md.
        /// </summary>
        internal static string PrivacyURL
        {
            get
            {
                return ResourceManager.GetString("PrivacyURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2.0.0.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
